#!/usr/bin/python

import os, sys, requests, json, logging

#TODO: scale these three parameters outside to connect with any user and to any IP
ip_address = '10.1.7.21'    #localhost???
sonata_user = 'sonata'
sonata_pwd = '1234'
base_url = 'http://'+ip_address+':32001/api/v2'


def connect2sonata():
    #prepares the parameters for the POST request
    url = base_url + '/sessions'
    data = '{"username":"' + sonata_user + '","password":"' + sonata_pwd + '"}'
    
    #sends the request to the Sonata Gatekeeper API
    response = requests.post(url, data).json()
    
    #looks for the token value generated by Sonata for the session
    token_array = response['token']
    for item_token in token_array:
      token = token_array['access_token']

    return token

def instantiation2sonata(token, service_uuid):
    #prepares the parameters for the POST request
    url = base_url + "/requests"
    headers_instantiation = {"authorization":"bearer " + str(token)}
    data_instantiation = {"service_uuid":service_uuid, "ingresses":[], "egresses":[]}
    
    #sends the request to the Sonata Gatekeeper API
    response = requests.post(url, headers=headers_instantiation, data=data_instantiation)
    jsonresponse = json.dumps(response, indent=4, sort_keys=True)

    return jsonresponse